// The type half of the umbrella surface lock. A runtime test can't observe erased
// types, so every re-exported type name is pulled in here and gathered into one
// exported tuple; `pnpm typecheck` compiles this file, and a removed or renamed
// re-export fails to resolve. umbrella-export-surface.test.ts references the tuple
// so the pair travels together.
import type {
  VestedResult,
  StatementContribution,
  SchedulePresentation,
  RecoveryOutcome,
  RecoveredTemplate,
  LintResult,
  Diagnostic,
  InferInput,
  InferResult,
  TrancheInput,
  DecompositionComponent,
  HypothesisFamily,
  RecoveryMode,
  Program,
  RawProgram,
  Statement,
  Schedule,
  ResolutionContextInput,
  AsOfContextInput,
  EvaluatedSchedule,
  Installment,
  ResolvedInstallment,
  UnresolvedInstallment,
  ImpossibleInstallment,
  Blocker,
  OCTDate,
} from "@vestlang/vestlang";

export type UmbrellaTypeSurface = readonly [
  VestedResult,
  StatementContribution,
  SchedulePresentation,
  RecoveryOutcome,
  RecoveredTemplate,
  LintResult,
  Diagnostic,
  InferInput,
  InferResult,
  TrancheInput,
  DecompositionComponent,
  HypothesisFamily,
  RecoveryMode,
  Program,
  RawProgram,
  Statement,
  Schedule,
  ResolutionContextInput,
  AsOfContextInput,
  EvaluatedSchedule,
  Installment,
  ResolvedInstallment,
  UnresolvedInstallment,
  ImpossibleInstallment,
  Blocker,
  OCTDate,
];
