name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - "apps/docs/**"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Don't use cache: pnpm here (it invokes pnpm before it's installed)
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: Use pnpm 9.x
        run: corepack prepare pnpm@9 --activate

      - name: Show pnpm version (debug)
        run: pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build website
        run: pnpm --filter @vestlang/docs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: apps/docs/build

